### ISSUE TITLE
Consider replacing RippleAPI with ripple-keypairs in coldwallet.html

### ISSUE THREAD

**Issue by matejr** [ripply-eu/ripply-eu.github.io#1]
Ripple-keypairs contains all functions that you need:

https://github.com/ripple/ripple-keypairs

You probably don't need whole RippleAPI.

**Comment by ripplyeu** [comment]
Thank you for your suggestion!

**Comment by ripplyeu** [comment]
Ripple-lib replaced with ripple-keypairs
